# Generated by Django 5.1.1 on 2024-11-11 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='events/'),
        ),
    ]
